### ISSUE TITLE
Rpt errors

### ISSUE THREAD

**Issue by Giallustio** [M1lkm8n/jbad#1]
14:21:46 jbad_structures\ind\ind_coltan_mine\jbad_ind_coltan_conv1_10.p3d: house, config class missing
14:21:47 jbad_structures\ind\ind_coltan_mine\jbad_ind_coltan_conv1_10.p3d: house, config class missing
14:22:10 jbad_structures\walls\wall\jbad_wall_cbrk_5_d.p3d: house, config class missing
14:22:11 jbad_structures\ind\ind_coltan_mine\jbad_misc_coltan_heap.p3d: house, config class missing
14:22:13 Land_jbad_House_c_3: Lock_1_Unlocked - unknown animation source Lock_1_Hide
14:22:14 jbad_structures\ind\ind_coltan_mine\jbad_ind_coltan_hopper.p3d: house, config class missing
14:22:14 jbad_structures\ind\ind_coltan_mine\jbad_ind_coltan_conv2.p3d: house, config class missing
14:22:58 Error: EntityAI SubSkeleton index was not initialized properly (repeated 0x in the last 60sec)
14:22:58 name: Land_jbad_Wall_L_2m5_gate, shape: jbad_structures\walls\wall_l\jbad_wall_l_2m5_gate.p3d, index: -1, matrices: 1

**Comment by M1lkm8n** [comment]
should be all fixed now. I went through each error
