### ISSUE TITLE
Unknown Animation Sources

### ISSUE THREAD

**Issue by ghost** [M1lkm8n/jbad#15]
15:37:28 Warning Message: Animation source Door_1 not found in config.bin/CfgVehicles/Land_jbad_wall_l1_gate_dam/
15:37:28 Land_jbad_wall_l1_gate_dam: Door_1_Handle - unknown animation source Door_1
15:37:28 Warning Message: Animation source Door_2 not found in config.bin/CfgVehicles/Land_jbad_wall_l1_gate_dam/

15:37:43 Land_jbad_House_c_3: Lock_1_Unlocked - unknown animation source Lock_1_Hide

**Comment by M1lkm8n** [comment]
fixed in new update
