### ISSUE TITLE
Doors dont open

### ISSUE THREAD

**Issue by CypeRevenge** [M1lkm8n/jbad#17]
(land_jbad_hanger_withdoor), when i place it ingame with Mapbuilder i can open the doors, its working all fine. But when i place it with Terrainbuilder and pack the Terrain and try it after ingame, i cant open the doors! 
error rpt file: jbad_structures\mil\hanger\jbad_hanger_withdoor.p3d: house, config class missing

**Comment by M1lkm8n** [comment]
fixed. improper class name change in the model config lead to the doors not working
