### ISSUE TITLE
Cannot create object with abstract type...

### ISSUE THREAD

**Issue by kurewe** [M1lkm8n/jbad#25]
I don't know if this belongs here or with the FFAA guys for Lythium. However, I thought I would start here. After updating my test server with the latest Jbad and today's Lythium update, I receive numerous messages about the 7 objects shown below. Any idea if this this an issue with the objects or would it be the way they are being called on the Lythium map?

Cannot create object with abstract type Land_jbad_Misc_Rubble (scope = private?)
Cannot create object with abstract type Land_jbad_Misc_Cable_Rugs1 (scope = private?)
Cannot create object with abstract type Land_jbad_Misc_Cable (scope = private?)
Cannot create object with abstract type Land_jbad_Misc_ConcBox (scope = private?)
Cannot create object with abstract type Land_jbad_Com_tower (scope = private?)
Cannot create object with abstract type Land_Jbad_most_stred30 (scope = private?)
Cannot create object with abstract type Land_jbad_market_stalls_01 (scope = private?)

**Comment by M1lkm8n** [comment]
Thank you. It's fixed but I'm going to wait to release an update so I can fix a few more things and let the FFAA test the new build

**Comment by kurewe** [comment]
Awesome! Thanks for the good work and quick response.

**Comment by M1lkm8n** [comment]
fixed
