### ISSUE TITLE
mod.cpp in addons directory

### ISSUE THREAD

**Issue by flexgrip** [M1lkm8n/jbad#26]
Hey there @M1lkm8n !

Obviously we love your mod. It's a classic.

Would you mind moving the mod.cpp into the root of the mod (it's proper location)? This will help the server tools index and attribute your mod properly on launch. It's not doing any good in the addons directory.

I would have done it and sent you a PR but you don't have any code in this repo.

Thanks!

**Comment by M1lkm8n** [comment]
done
