### ISSUE TITLE
Fragile buildings

### ISSUE THREAD

**Issue by BonSie** [M1lkm8n/jbad#28]
Some buildings are very easily destroyed by machine gun fire. The worst offenders appear to be the middle eastern sand coloured buildings. Map was Lythium

I should have a test session recorded and I can probably get a RPT log from the admin if needed.

**Comment by M1lkm8n** [comment]
thank you. any more info you can give makes it easier to fix. so if you can link a video and post what version of jbad you are using that would be helpful. I think we rolled out a updated that fixed (or at least we think) the damage values of the buildings

**Comment by BonSie** [comment]
Version used is whatever is currently on the workshop. Vehicle is based of an RHS M113 (3CB Factions)
Dunno if there is an easier way to test the buildings.

https://plays.tv/s/M8DkkMhcZcEy

**Comment by tyl3r99** [comment]
yep a m240 with rhs can kill a building in like 15 rounds... were using latest version to date on steam workshop . 30/3/19

we use ACE and RHS 
maybe boost all the healths up due to rhs?

**Comment by tyl3r99** [comment]
was wondering if you had any progress :) thanks in advance

**Comment by veteran29** [comment]
I've created small addon to fix this issue by using `armor` value of CUP equivalent buildings:
https://steamcommunity.com/sharedfiles/filedetails/?id=1781106281

For now I've fixed only the big villa and "l-shaped" building (House 8). If I will identify more broken buildings I will try to fix them too. (It's only `armor` value change)

**Comment by M1lkm8n** [comment]
fixed and will be released in the next update
