### ISSUE TITLE
Bullet penetration

### ISSUE THREAD

**Issue by Giallustio** [M1lkm8n/jbad#3]
A lot of buildings (probably all) can't hold bullets.

http://cloud-4.steampowered.com/ugc/36358908599058219/7F5A3F2EA56E7E0853ECA6AF54458A682AD80B95/

http://cloud-4.steampowered.com/ugc/36358908599056638/282B757F20F6C5832C5B03D3D965C9E6B23A885F/

**Comment by M1lkm8n** [comment]
works fine on my end.tested on multiple buildings and units with different round types
