### ISSUE TITLE
Some .rpt errors, when game start, after last update

### ISSUE THREAD

**Issue by exYU** [M1lkm8n/jbad#33]
17:05:41 Conflicting addon Ind_Garage01 in 'Jbad_Structures\ind\ind_garage01\', previous definition in 'ca\buildings2_c\ind_garage01\'
17:05:41 Conflicting addon Ind_Workshop01 in 'Jbad_Structures\ind\ind_workshop01\', previous definition in 'ca\buildings2_c\ind_workshop01\'

**Comment by M1lkm8n** [comment]
added Jbad tag
