### ISSUE TITLE
AI get stuck in walls

### ISSUE THREAD

**Issue by ghost** [M1lkm8n/jbad#6]
Not sure why but i'm getting reports AI are getting stuck in the walls, maybe it's because the walls are classed as Houses and the path lod is defining entry points? The path lod has a named selection that is unhide but perhaps this isn't working as intended.

Maybe the trade off has to be that when the walls are destroyed they still navigate as if the walls are there... and only use the gates etc.

**Comment by M1lkm8n** [comment]
adjusted lods of walls. ai should be ok now

**Comment by M1lkm8n** [comment]
fixed wall destruction..should have fixed this error
